
import { Language } from './types';

export const LANGUAGES: { value: Language; label: string }[] = [
  { value: 'EN', label: 'English' },
  { value: 'UZ', label: 'O\'zbek (Uzbek)' },
  { value: 'RU', label: 'Русский (Russian)' },
];

const BASE_RULES = `
STYLE RULES:
- Short bullet points only (1–5 bullets per slide).
- No long paragraphs. No emojis. No decorative symbols.
- Formal academic or business tone.
- Concise, presentation-ready phrasing.

SLIDE STRUCTURE (MANDATORY ORDER):
1. Title Slide (Presentation title derived from topic)
2. Overview / Agenda (3–6 bullet points summarizing scope)
3. Main Content (3–7 slides focusing on key concepts, arguments, findings)
4. Final Slide: Summary / Conclusion (Key takeaways)
`;

export const DOCUMENT_SYSTEM_PROMPT = `
You are an AI agent that converts uploaded documents into clear, structured, presentation-ready slide content.
${BASE_RULES}
LANGUAGE RULES:
- Generate content ONLY in the user-selected language.
- Translate and adapt content if the source differs.
`;

export const YOUTUBE_SYSTEM_PROMPT = `
You are an AI agent that converts YouTube video transcripts into professional presentation-ready slide content.
TRANSCRIPT CLEANING RULES:
- Remove greetings, filler words (um, ah, like, you know), ads/sponsorship segments, and repetitive phrases.
- Convert spoken language into formal, structured text.
${BASE_RULES}
LANGUAGE RULES:
- Generate content ONLY in the user-selected language.
- Translate and adapt content if the source differs.
`;

export const PPTX_GENERATION_PROMPT = `
# Role: Python Automation Engineer (python-pptx specialist)
# Task: Create a script to generate a PowerPoint (.pptx) file from a JSON input.

import json
from pptx import Presentation
from pptx.util import Inches, Pt

def create_pptx(json_data, output_file="presentation.pptx"):
    data = json.loads(json_data)
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = data.get("title", "Untitled Presentation")
    subtitle.text = "Generated by Antigravity AI"

    # Content Slides
    for slide_data in data.get("slides", []):
        layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(layout)
        title_shape = slide.shapes.title
        title_shape.text = slide_data.get("title", "No Title")
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        for bullet in slide_data.get("bullets", []):
            p = tf.add_paragraph()
            p.text = bullet
            p.level = 0

    prs.save(output_file)
    return output_file
`;

export const PPTX_API_SCHEMA = {
  endpoint: "POST /api/v1/export/pptx",
  request_body: {
    title: "string",
    slides: [{ title: "string", bullets: ["string"] }]
  }
};
